name: Build Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adoptopenjdk'

    - name: Compile Java code
      run: |
        mkdir -p bin
        javac -d bin JavaUtil.java

    - name: Create JAR file
      run: |
        jar -cvf ZipUtil.jar -C bin .
